var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];
export function randomNames() {
  var finalName = nameList[Math.floor(Math.random() * nameList.length)];

  return finalName;
}

export function randomComments() {
  const comments = [
    "What a magnificent shot! 🏏🔥",
    "That's a huge six! 💥🎯",
    "Brilliant cover drive! 👏",
    "Unbelievable catch! 🤯",
    "Bowled him! 🎳",
    "The crowd is going wild! 🎉",
    "Great fielding effort! 🛡️",
    "A well-timed boundary! 🎯",
    "What a delivery! 🎯🔥",
    "A superb fifty! 🏏💯",
    "That's out! Umpire raises the finger! ☝️",
    "Incredible yorker! 🎯",
    "Smashed it for a six! 💪",
    "A brilliant spell of bowling! 🎳🔥",
    "The batsman is in top form today! 💪",
    "Glorious straight drive! 🤩",
    "What a stunning reverse sweep! 🏏",
    "It's a nail-biting finish! 😱",
    "An excellent partnership building up! 🤝",
    "That was a risky single! 🏃",
    "Fantastic pull shot! 🔥",
    "He's taken him to the cleaners! 💣",
    "A textbook cover drive! 📖🏏",
    "Sensational all-round performance! 👏",
    "The bowler is on fire! 🔥",
    "A crucial breakthrough! 🚀",
    "The game is slipping away! ⚠️",
    "Smart captaincy on display! 🎩",
    "That was plumb! No doubt about it! ☝️",
    "A brilliant slower ball! 🌀",
    "He's playing with a lot of confidence! 💪",
    "Edge and taken! 🎣",
    "That was an absolute ripper! 🎳🔥",
    "Pressure is building up! 😨",
    "A fantastic hundred! 💯🎉",
    "Great sportsmanship on display! 🤝",
    "That ball swung a mile! 🌀",
    "The bowler is setting up the batsman! 🎯",
    "What an exciting match! 🔥🔥",
  ];

  const randomIndex = Math.floor(Math.random() * comments.length);
  return comments[randomIndex];
}

// Example usage
